#   Welcome to the feedtype declaration for the modo_stackexchange feedtype!

---
title: Stack Exchange Feed                                                              # The human readable title for this feedtype
dataObjects:                                                                            # The data objects this feedtype manages
-   KGODataObject
-   ModoStackExchangeQuestionDataObject
args:                                                                                   # The arguments to be set for feeds with this feedtype
    dataModel: ModoStackExchangeDataModel
    dataRetriever: ModoStackExchangeDataRetriever
    dataParser: KGOJSONDataParser
    processors:
        preprocessor:                                                                   # A prepocessor is run on the raw data returned by the DataRetriever
        -   class: ModoStackExchangeDataProcessor                                       # The Stack Exchange API compresses all of its responses. The ModoStackExchangeDataProcessor will decompress the response into the JSON we know and love. http://api.stackexchange.com/docs/compression
config:                                                                                 # 'config' is an objdef used by the Kurogo Admin Console to display a UI to further configure the feed instance.
-   class: KGOFormElementControllerText                                                 # KGOFormElementController is a descendant of KGODataController
    validators: []                                                                      # it is possible to attach KGOValidators to fields to validate admin user input
    options:
        required: false
    fields:
        label: Stack Exchange Site
        description: The Stack Exchange Site to explore
    controller:
        config: site                                                                    # The 'controller' 'config' is used to define what config argument is set with the user input
-   class: KGOFormElementControllerText
    options:
        required: false
    fields:
        label: API Key
        description: The API key used to authorize requests
    controller:
        config: apiKey
-   class: KGOFormElementControllerText
    options:
        required: false
    fields:
        label: API Version
        description: The API version to use for requests. Defaults to 2.1
    controller:
        config: apiVersion
...
