---
common:
    pages:
        index:
            objdefs:
                content: page-index.objdefs.content.default
        search:
            pageTitle: Search Results
            objdefs:
                content: page-search.objdefs.content.default
        detail:
            objdefs:
                content: page-detail.objdefs.content.default
...
