---
common:
    objdefs:
        content:
            default:
            -   class: KGODetailController
                uiClass: KGOUIDetailStackExchange
                source:
                -   kgoResolveType: method
                    kgoResolveValue: getFeed
                -   kgoResolveType: method
                    kgoResolveValue: getItem
                options:
                        bookmarkable: false
                fields:
                    title:
                        kgoResolveType: value
                        kgoResolveValue: kgo:title
                    thumbnail:
                        kgoResolveType: value
                        kgoResolveValue: profile_image
                        kgoResolveProcessors:
                        -   class: KGOImageDataProcessor
                            options:
                                maxHeight: 60
                    author:
                        kgoResolveType: value
                        kgoResolveValue: author
                regions:
                -   name: content
                    contents:
                    -   class: KGODataController
                        uiClass: KGOUIHTML
                        fields:
                            html:
                                kgoResolveType: value
                                kgoResolveValue: body
                    -   class: KGOListController
                        requiresData: false
                        options:
                            grouped: false
                            inset: true
                        fields:
                            heading: Answers
                            noItemsMessage: No answers
                        regions:
                        -   name: items
                            contents:
                            -   class: KGOListItemController
                                uiClass: KGOUIListItemSEAnswer
                                source:
                                -   kgoResolveType: method
                                    kgoResolveValue: getAnswers
                                fields:
                                    title:
                                        kgoResolveType: value
                                        kgoResolveValue: body
                                    label:
                                        kgoResolveType: value
                                        kgoResolveValue: score
                                fieldFormatters:    
                                    title:
                                    -   class: KGOHTMLFormatter
...