---
common:
    objdefs:
        content:
            default:
            -   class: KGODataController
                uiClass: KGOUISearchModoStackExchange
            -   class: KGOListController
                requiresData: false
                options:
                    grouped: true
                    urlCommand: detail
                fields:
                    heading:
                        kgoResolveType: localize
                        kgoResolveValue: modo_stack_exchange.headings.featuredQuestions
                    noItemsMessage:
                        kgoResolveType: localize
                        kgoResolveValue: modo_stack_exchange.error.noFeaturedQuestions
                regions:
                -   name: items
                    contents:
                    -   class: KGOListItemController
                        source:
                        -   kgoResolveType: method
                            kgoResolveValue: getFeaturedQuestions
...