---
common:
    objdefs:
        content:
            default:
            -   class: KGODataController
                uiClass: KGOUISearchStackExchange
            -   class: KGOListController
                requiresData: false
                options:
                    grouped: true
                    urlCommand: detail
                fields:
                    heading: Featured Questions
                    noItemsMessage: Unable to retrieve featured questions
                regions:
                -   name: items
                    contents:
                    -   class: KGOListItemController
                        source:
                        -   kgoResolveType: method
                            kgoResolveValue: getFeaturedQuestions
...